// Helper: cria um bloco de código multi-linha sem problemas com template literals
const L = (...lines) => lines.join('\n');

const go = [
  // ─── BÁSICO ────────────────────────────────────────────────────────────────
  {
    nivel: "basico",
    enunciado: "Escreva um programa Go que exibe 'Olá, Mundo!' no terminal.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'func main() {',
      '    fmt.Println("Olá, Mundo!")',
      '}',
    ),
  },
  {
    nivel: "basico",
    enunciado: "Declare variáveis com var e := e exiba seus tipos com fmt.Printf.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'func main() {',
      '    var nome string = "Matheus"',
      '    idade := 25',
      '    altura := 1.75',
      '    fmt.Printf("Nome: %s, Idade: %d, Altura: %.2f\\n", nome, idade, altura)',
      '    fmt.Printf("Tipos: %T %T %T\\n", nome, idade, altura)',
      '}',
    ),
  },
  {
    nivel: "basico",
    enunciado: "Crie uma função que recebe dois inteiros e retorna a soma e o produto.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'func calcular(a, b int) (int, int) {',
      '    return a + b, a * b',
      '}',
      '',
      'func main() {',
      '    soma, produto := calcular(4, 5)',
      '    fmt.Println("Soma:", soma, "| Produto:", produto)',
      '}',
    ),
  },
  {
    nivel: "basico",
    enunciado: "Use um slice para armazenar nomes e itere com range.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'func main() {',
      '    nomes := []string{"Matheus", "João", "Maria"}',
      '    for i, nome := range nomes {',
      '        fmt.Printf("%d: %s\\n", i+1, nome)',
      '    }',
      '}',
    ),
  },
  {
    nivel: "basico",
    enunciado: "Crie um map para associar nomes a idades e itere sobre ele.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'func main() {',
      '    idades := map[string]int{',
      '        "Matheus": 25,',
      '        "João":    30,',
      '        "Maria":   22,',
      '    }',
      '    for nome, idade := range idades {',
      '        fmt.Printf("%s tem %d anos\\n", nome, idade)',
      '    }',
      '}',
    ),
  },
  {
    nivel: "basico",
    enunciado: "Defina uma struct Usuario com campos Nome e Email.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'type Usuario struct {',
      '    Nome  string',
      '    Email string',
      '}',
      '',
      'func main() {',
      '    u := Usuario{Nome: "Matheus", Email: "m@email.com"}',
      '    fmt.Printf("Usuário: %s <%s>\\n", u.Nome, u.Email)',
      '}',
    ),
  },
  {
    nivel: "basico",
    enunciado: "Trate o segundo retorno de erro de uma função Go.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "errors"',
      '    "fmt"',
      ')',
      '',
      'func dividir(a, b float64) (float64, error) {',
      '    if b == 0 {',
      '        return 0, errors.New("divisão por zero")',
      '    }',
      '    return a / b, nil',
      '}',
      '',
      'func main() {',
      '    resultado, err := dividir(10, 0)',
      '    if err != nil {',
      '        fmt.Println("Erro:", err)',
      '        return',
      '    }',
      '    fmt.Println("Resultado:", resultado)',
      '}',
    ),
  },
  {
    nivel: "basico",
    enunciado: "Use defer para garantir que um recurso seja liberado ao final da função.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'func abrirConexao() string { return "conexão aberta" }',
      'func fecharConexao()       { fmt.Println("Conexão fechada") }',
      '',
      'func processar() {',
      '    fmt.Println(abrirConexao())',
      '    defer fecharConexao()',
      '    fmt.Println("Processando...")',
      '}',
      '',
      'func main() { processar() }',
    ),
  },
  {
    nivel: "basico",
    enunciado: "Crie e use um ponteiro para modificar o valor de uma variável externa.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'func dobrar(n *int) {',
      '    *n *= 2',
      '}',
      '',
      'func main() {',
      '    valor := 5',
      '    dobrar(&valor)',
      '    fmt.Println(valor) // 10',
      '}',
    ),
  },
  {
    nivel: "basico",
    enunciado: "Implemente uma função recursiva para calcular a sequência de Fibonacci.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'func fibonacci(n int) int {',
      '    if n <= 1 { return n }',
      '    return fibonacci(n-1) + fibonacci(n-2)',
      '}',
      '',
      'func main() {',
      '    for i := 0; i <= 9; i++ {',
      '        fmt.Printf("F(%d) = %d\\n", i, fibonacci(i))',
      '    }',
      '}',
    ),
  },

  // ─── INTERMEDIÁRIO ─────────────────────────────────────────────────────────
  {
    nivel: "intermediario",
    enunciado: "Adicione métodos a uma struct e implemente uma interface.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'type Animal interface {',
      '    Falar() string',
      '}',
      '',
      'type Cachorro struct{ Nome string }',
      'type Gato     struct{ Nome string }',
      '',
      'func (c Cachorro) Falar() string { return c.Nome + " diz: Au Au!" }',
      'func (g Gato)     Falar() string { return g.Nome + " diz: Miau!" }',
      '',
      'func fazerBarulho(a Animal) { fmt.Println(a.Falar()) }',
      '',
      'func main() {',
      '    fazerBarulho(Cachorro{Nome: "Rex"})',
      '    fazerBarulho(Gato{Nome: "Felix"})',
      '}',
    ),
  },
  {
    nivel: "intermediario",
    enunciado: "Use goroutines e WaitGroup para processar trabalhos em paralelo.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "fmt"',
      '    "sync"',
      ')',
      '',
      'func processar(id int, wg *sync.WaitGroup) {',
      '    defer wg.Done()',
      '    fmt.Printf("Goroutine %d concluída\\n", id)',
      '}',
      '',
      'func main() {',
      '    var wg sync.WaitGroup',
      '    for i := 1; i <= 5; i++ {',
      '        wg.Add(1)',
      '        go processar(i, &wg)',
      '    }',
      '    wg.Wait()',
      '    fmt.Println("Tudo concluído")',
      '}',
    ),
  },
  {
    nivel: "intermediario",
    enunciado: "Implemente um pipeline com channels para transformar dados.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'func gerar(nums ...int) <-chan int {',
      '    out := make(chan int)',
      '    go func() {',
      '        for _, n := range nums { out <- n }',
      '        close(out)',
      '    }()',
      '    return out',
      '}',
      '',
      'func duplicar(in <-chan int) <-chan int {',
      '    out := make(chan int)',
      '    go func() {',
      '        for n := range in { out <- n * 2 }',
      '        close(out)',
      '    }()',
      '    return out',
      '}',
      '',
      'func main() {',
      '    for n := range duplicar(gerar(1, 2, 3, 4, 5)) {',
      '        fmt.Println(n)',
      '    }',
      '}',
    ),
  },
  {
    nivel: "intermediario",
    enunciado: "Faça uma requisição HTTP e processe a resposta JSON.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "encoding/json"',
      '    "fmt"',
      '    "net/http"',
      ')',
      '',
      '// Struct sem tags para simplificar (tags usam backticks em Go)',
      'type Post struct {',
      '    ID    int',
      '    Title string',
      '}',
      '',
      'func main() {',
      '    resp, err := http.Get("https://jsonplaceholder.typicode.com/posts/1")',
      '    if err != nil { panic(err) }',
      '    defer resp.Body.Close()',
      '',
      '    var post Post',
      '    json.NewDecoder(resp.Body).Decode(&post)',
      '    fmt.Printf("Post #%d: %s\\n", post.ID, post.Title)',
      '}',
    ),
  },
  {
    nivel: "intermediario",
    enunciado: "Serialize e desserialize uma struct para JSON.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "encoding/json"',
      '    "fmt"',
      ')',
      '',
      '// Em Go, tags de struct usam backticks: `json:"campo"`',
      '// Exemplo: Nome string `json:"nome"`',
      '',
      'type Usuario struct {',
      '    Nome  string',
      '    Email string',
      '    Idade int',
      '}',
      '',
      'func main() {',
      '    u := Usuario{Nome: "Matheus", Email: "m@email.com", Idade: 25}',
      '    dados, _ := json.MarshalIndent(u, "", "  ")',
      '    fmt.Println(string(dados))',
      '',
      '    var u2 Usuario',
      '    json.Unmarshal(dados, &u2)',
      '    fmt.Println(u2.Nome)',
      '}',
    ),
  },
  {
    nivel: "intermediario",
    enunciado: "Crie um servidor HTTP básico com net/http.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "encoding/json"',
      '    "net/http"',
      ')',
      '',
      'func usersHandler(w http.ResponseWriter, r *http.Request) {',
      '    w.Header().Set("Content-Type", "application/json")',
      '    json.NewEncoder(w).Encode([]map[string]string{',
      '        {"nome": "Matheus", "email": "m@email.com"},',
      '    })',
      '}',
      '',
      'func main() {',
      '    http.HandleFunc("/users", usersHandler)',
      '    http.ListenAndServe(":8080", nil)',
      '}',
    ),
  },
  {
    nivel: "intermediario",
    enunciado: "Use context.Context para cancelar operações longas.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "context"',
      '    "fmt"',
      '    "time"',
      ')',
      '',
      'func tarefaLonga(ctx context.Context) error {',
      '    select {',
      '    case <-time.After(5 * time.Second):',
      '        return nil',
      '    case <-ctx.Done():',
      '        return ctx.Err()',
      '    }',
      '}',
      '',
      'func main() {',
      '    ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)',
      '    defer cancel()',
      '    if err := tarefaLonga(ctx); err != nil {',
      '        fmt.Println("Cancelado:", err)',
      '    }',
      '}',
    ),
  },
  {
    nivel: "intermediario",
    enunciado: "Leia e escreva arquivos com os pacotes os e bufio.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "bufio"',
      '    "fmt"',
      '    "os"',
      ')',
      '',
      'func main() {',
      '    os.WriteFile("usuarios.txt", []byte("Matheus\\nJoão\\nMaria"), 0644)',
      '',
      '    f, _ := os.Open("usuarios.txt")',
      '    defer f.Close()',
      '    scanner := bufio.NewScanner(f)',
      '    for scanner.Scan() {',
      '        fmt.Println(scanner.Text())',
      '    }',
      '}',
    ),
  },
  {
    nivel: "intermediario",
    enunciado: "Implemente um pool de workers com channels.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "fmt"',
      '    "sync"',
      ')',
      '',
      'func worker(id int, jobs <-chan int, results chan<- int, wg *sync.WaitGroup) {',
      '    defer wg.Done()',
      '    for j := range jobs {',
      '        results <- j * j',
      '        fmt.Printf("Worker %d processou job %d\\n", id, j)',
      '    }',
      '}',
      '',
      'func main() {',
      '    jobs, results := make(chan int, 10), make(chan int, 10)',
      '    var wg sync.WaitGroup',
      '    for i := 1; i <= 3; i++ { wg.Add(1); go worker(i, jobs, results, &wg) }',
      '    for j := 1; j <= 6; j++ { jobs <- j }',
      '    close(jobs)',
      '    wg.Wait(); close(results)',
      '    for r := range results { fmt.Println("Resultado:", r) }',
      '}',
    ),
  },
  {
    nivel: "intermediario",
    enunciado: "Use type embedding para compor structs.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'type Base struct {',
      '    ID   int',
      '    Nome string',
      '}',
      '',
      'func (b Base) Exibir() {',
      '    fmt.Printf("ID: %d, Nome: %s\\n", b.ID, b.Nome)',
      '}',
      '',
      'type Produto struct {',
      '    Base',
      '    Preco float64',
      '}',
      '',
      'func main() {',
      '    p := Produto{Base: Base{ID: 1, Nome: "Notebook"}, Preco: 3500.00}',
      '    p.Exibir()',
      '    fmt.Printf("Preço: R$ %.2f\\n", p.Preco)',
      '}',
    ),
  },

  // ─── AVANÇADO ──────────────────────────────────────────────────────────────
  {
    nivel: "avancado",
    enunciado: "Implemente um servidor HTTP com middleware de autenticação.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "fmt"',
      '    "net/http"',
      '    "strings"',
      ')',
      '',
      'func autenticar(next http.Handler) http.Handler {',
      '    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {',
      '        token := r.Header.Get("Authorization")',
      '        if !strings.HasPrefix(token, "Bearer ") {',
      '            http.Error(w, "Não autorizado", http.StatusUnauthorized)',
      '            return',
      '        }',
      '        next.ServeHTTP(w, r)',
      '    })',
      '}',
      '',
      'func main() {',
      '    mux := http.NewServeMux()',
      '    mux.HandleFunc("/api/dados", func(w http.ResponseWriter, r *http.Request) {',
      '        fmt.Fprintln(w, `{"dados": "secretos"}`)',
      '    })',
      '    http.ListenAndServe(":8080", autenticar(mux))',
      '}',
    ),
  },
  {
    nivel: "avancado",
    enunciado: "Implemente um cache thread-safe com sync.RWMutex e generics.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "fmt"',
      '    "sync"',
      ')',
      '',
      'type Cache[V any] struct {',
      '    mu    sync.RWMutex',
      '    dados map[string]V',
      '}',
      '',
      'func NovoCache[V any]() *Cache[V] {',
      '    return &Cache[V]{dados: make(map[string]V)}',
      '}',
      '',
      'func (c *Cache[V]) Set(k string, v V) {',
      '    c.mu.Lock(); defer c.mu.Unlock()',
      '    c.dados[k] = v',
      '}',
      '',
      'func (c *Cache[V]) Get(k string) (V, bool) {',
      '    c.mu.RLock(); defer c.mu.RUnlock()',
      '    v, ok := c.dados[k]',
      '    return v, ok',
      '}',
      '',
      'func main() {',
      '    cache := NovoCache[string]()',
      '    cache.Set("usuario:1", "Matheus")',
      '    if v, ok := cache.Get("usuario:1"); ok {',
      '        fmt.Println(v)',
      '    }',
      '}',
    ),
  },
  {
    nivel: "avancado",
    enunciado: "Use generics (Go 1.18+) para criar funções Filter e Map genéricas.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'func Filter[T any](slice []T, fn func(T) bool) []T {',
      '    var resultado []T',
      '    for _, item := range slice {',
      '        if fn(item) { resultado = append(resultado, item) }',
      '    }',
      '    return resultado',
      '}',
      '',
      'func Map[T, U any](slice []T, fn func(T) U) []U {',
      '    resultado := make([]U, len(slice))',
      '    for i, item := range slice { resultado[i] = fn(item) }',
      '    return resultado',
      '}',
      '',
      'func main() {',
      '    nums   := []int{1, 2, 3, 4, 5, 6}',
      '    pares  := Filter(nums, func(n int) bool { return n%2 == 0 })',
      '    dobros := Map(pares, func(n int) int { return n * 2 })',
      '    fmt.Println(dobros) // [4 8 12]',
      '}',
    ),
  },
  {
    nivel: "avancado",
    enunciado: "Implemente rate limiting com time.Ticker.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "fmt"',
      '    "time"',
      ')',
      '',
      'type RateLimiter struct{ tokens chan struct{} }',
      '',
      'func NovoLimiter(taxa, burst int) *RateLimiter {',
      '    tokens := make(chan struct{}, burst)',
      '    for i := 0; i < burst; i++ { tokens <- struct{}{} }',
      '    go func() {',
      '        ticker := time.NewTicker(time.Second / time.Duration(taxa))',
      '        for range ticker.C {',
      '            select {',
      '            case tokens <- struct{}{}:',
      '            default:',
      '            }',
      '        }',
      '    }()',
      '    return &RateLimiter{tokens: tokens}',
      '}',
      '',
      'func (r *RateLimiter) Permitir() bool {',
      '    select {',
      '    case <-r.tokens: return true',
      '    default:         return false',
      '    }',
      '}',
      '',
      'func main() {',
      '    limiter := NovoLimiter(2, 5)',
      '    for i := 0; i < 7; i++ { fmt.Println(i, ":", limiter.Permitir()) }',
      '}',
    ),
  },
  {
    nivel: "avancado",
    enunciado: "Escreva testes de benchmark com testing.B.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "strings"',
      '    "testing"',
      ')',
      '',
      'func concatenarLoop(partes []string) string {',
      '    resultado := ""',
      '    for _, p := range partes { resultado += p }',
      '    return resultado',
      '}',
      '',
      'func concatenarBuilder(partes []string) string {',
      '    var sb strings.Builder',
      '    for _, p := range partes { sb.WriteString(p) }',
      '    return sb.String()',
      '}',
      '',
      'func BenchmarkLoop(b *testing.B) {',
      '    partes := make([]string, 100)',
      '    for i := range partes { partes[i] = "teste" }',
      '    for i := 0; i < b.N; i++ { concatenarLoop(partes) }',
      '}',
      '',
      'func BenchmarkBuilder(b *testing.B) {',
      '    partes := make([]string, 100)',
      '    for i := range partes { partes[i] = "teste" }',
      '    for i := 0; i < b.N; i++ { concatenarBuilder(partes) }',
      '}',
    ),
  },
  {
    nivel: "avancado",
    enunciado: "Implemente o padrão functional options para configuração.",
    solucao: L(
      'package main',
      '',
      'import "fmt"',
      '',
      'type Servidor struct {',
      '    host    string',
      '    porta   int',
      '    timeout int',
      '}',
      '',
      'type Opcao func(*Servidor)',
      '',
      'func ComHost(h string) Opcao  { return func(s *Servidor) { s.host = h } }',
      'func ComPorta(p int) Opcao    { return func(s *Servidor) { s.porta = p } }',
      'func ComTimeout(t int) Opcao  { return func(s *Servidor) { s.timeout = t } }',
      '',
      'func NovoServidor(opts ...Opcao) *Servidor {',
      '    s := &Servidor{host: "localhost", porta: 8080, timeout: 30}',
      '    for _, o := range opts { o(s) }',
      '    return s',
      '}',
      '',
      'func main() {',
      '    s := NovoServidor(ComPorta(9090), ComTimeout(60))',
      '    fmt.Printf("%+v\\n", s)',
      '}',
    ),
  },
  {
    nivel: "avancado",
    enunciado: "Use reflect para inspecionar campos de uma struct dinamicamente.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "fmt"',
      '    "reflect"',
      ')',
      '',
      'type Produto struct {',
      '    Nome    string',
      '    Preco   float64',
      '    Estoque int',
      '}',
      '',
      'func inspecionar(v any) {',
      '    t   := reflect.TypeOf(v)',
      '    val := reflect.ValueOf(v)',
      '    for i := 0; i < t.NumField(); i++ {',
      '        campo := t.Field(i)',
      '        valor := val.Field(i)',
      '        fmt.Printf("Campo: %-10s | Tipo: %-8s | Valor: %v\\n",',
      '            campo.Name, campo.Type, valor)',
      '    }',
      '}',
      '',
      'func main() {',
      '    inspecionar(Produto{Nome: "Notebook", Preco: 3500, Estoque: 10})',
      '}',
    ),
  },
  {
    nivel: "avancado",
    enunciado: "Implemente um Circuit Breaker simples.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "errors"',
      '    "fmt"',
      '    "time"',
      ')',
      '',
      'type Estado int',
      'const (Fechado Estado = iota; Aberto; MeioAberto)',
      '',
      'type CircuitBreaker struct {',
      '    estado      Estado',
      '    falhas      int',
      '    limite      int',
      '    ultimaFalha time.Time',
      '    timeout     time.Duration',
      '}',
      '',
      'func (cb *CircuitBreaker) Executar(fn func() error) error {',
      '    if cb.estado == Aberto {',
      '        if time.Since(cb.ultimaFalha) > cb.timeout {',
      '            cb.estado = MeioAberto',
      '        } else {',
      '            return errors.New("circuito aberto")',
      '        }',
      '    }',
      '    err := fn()',
      '    if err != nil {',
      '        cb.falhas++; cb.ultimaFalha = time.Now()',
      '        if cb.falhas >= cb.limite { cb.estado = Aberto }',
      '    } else {',
      '        cb.falhas = 0; cb.estado = Fechado',
      '    }',
      '    return err',
      '}',
      '',
      'func main() {',
      '    cb := &CircuitBreaker{limite: 3, timeout: 5 * time.Second}',
      '    for i := 0; i < 5; i++ {',
      '        err := cb.Executar(func() error { return errors.New("falha") })',
      '        fmt.Println(i, ":", err)',
      '    }',
      '}',
    ),
  },
  {
    nivel: "avancado",
    enunciado: "Escreva testes com table-driven tests.",
    solucao: L(
      'package main',
      '',
      'import "testing"',
      '',
      'func soma(a, b int) int { return a + b }',
      '',
      'func TestSoma(t *testing.T) {',
      '    casos := []struct {',
      '        nome     string',
      '        a, b     int',
      '        esperado int',
      '    }{',
      '        {"positivos", 2, 3, 5},',
      '        {"negativos", -2, -3, -5},',
      '        {"zero",      0,  5,  5},',
      '        {"misto",    -1,  1,  0},',
      '    }',
      '    for _, tc := range casos {',
      '        t.Run(tc.nome, func(t *testing.T) {',
      '            if r := soma(tc.a, tc.b); r != tc.esperado {',
      '                t.Errorf("soma(%d,%d)=%d; esperado %d", tc.a, tc.b, r, tc.esperado)',
      '            }',
      '        })',
      '    }',
      '}',
    ),
  },
  {
    nivel: "avancado",
    enunciado: "Implemente pub/sub em memória com goroutines e channels.",
    solucao: L(
      'package main',
      '',
      'import (',
      '    "fmt"',
      '    "sync"',
      ')',
      '',
      'type PubSub struct {',
      '    mu      sync.RWMutex',
      '    topicos map[string][]chan string',
      '}',
      '',
      'func NovoPubSub() *PubSub { return &PubSub{topicos: make(map[string][]chan string)} }',
      '',
      'func (ps *PubSub) Assinar(topico string) <-chan string {',
      '    ch := make(chan string, 10)',
      '    ps.mu.Lock(); defer ps.mu.Unlock()',
      '    ps.topicos[topico] = append(ps.topicos[topico], ch)',
      '    return ch',
      '}',
      '',
      'func (ps *PubSub) Publicar(topico, msg string) {',
      '    ps.mu.RLock(); defer ps.mu.RUnlock()',
      '    for _, ch := range ps.topicos[topico] { ch <- msg }',
      '}',
      '',
      'func main() {',
      '    ps := NovoPubSub()',
      '    ch := ps.Assinar("noticias")',
      '    ps.Publicar("noticias", "Go 2.0 lançado!")',
      '    fmt.Println(<-ch)',
      '}',
    ),
  },
];

export default go;
